### ISSUE TITLE
Not Able to search with domain name

### ISSUE THREAD

**Issue by hunter0x8** [Healdb/Elevate#1]
![image](https://user-images.githubusercontent.com/46222314/83075292-0ac90300-a08d-11ea-83ac-41b197dd6556.png)
![image](https://user-images.githubusercontent.com/46222314/83075345-1ddbd300-a08d-11ea-9fd8-f43536be580f.png)
![image](https://user-images.githubusercontent.com/46222314/83075396-32b86680-a08d-11ea-9690-33af0705a536.png)
![image](https://user-images.githubusercontent.com/46222314/83075424-44017300-a08d-11ea-9d7e-0e5dc6bed869.png)

**Comment by hunter0x8** [comment]
Added the api keys in config.txt still getting 0

**Comment by Healdb** [comment]
Try it a few times, and see if you can connect to the API's through some other program to verify that the API keys are correct.

**Comment by Ahsan-x** [comment]
Still getting issue 
![image](https://user-images.githubusercontent.com/46222314/83077480-eec76080-a090-11ea-8596-8aabc1e03cb5.png)

![image](https://user-images.githubusercontent.com/46222314/83077541-0c94c580-a091-11ea-951d-5610866c8504.png)

![image](https://user-images.githubusercontent.com/46222314/83077600-30f0a200-a091-11ea-94fa-9abb7435694f.png)

![image](https://user-images.githubusercontent.com/46222314/83077660-4fef3400-a091-11ea-8dc9-17f26e1416ba.png)

change the program facebook,google,and reddit nothing works

**Comment by Healdb** [comment]
Do you have WHOXY reverse whois api credits in your account? The balance should show under your whoxy api balance
![Capture](https://user-images.githubusercontent.com/6737684/83078349-408acf00-a02e-11ea-9021-db1de0797905.PNG)

**Comment by hunter0x8** [comment]
Nope i think i haven't have any reverse whois api credits in account. I thought it would be free but it is not we have to buy credit. By the way thanks for the help it was nice talking to you.!
![image](https://user-images.githubusercontent.com/46222314/83078690-93e33880-a093-11ea-934e-a7877b42df47.png)
